stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image:
    name: "registrydocker.ewo.com:5000/rpi_yocto_build"
  tags:
    - build-c
  script:
    - source sources/poky/oe-init-build-env
    - bitbake swupdate-image-fullcmdline

